"""empty message

Revision ID: 625ed39f8289
Revises: 8351cd9e79fc
Create Date: 2025-02-26 20:27:09.697337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625ed39f8289'
down_revision = '8351cd9e79fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_climate_key', type_='unique')
        batch_op.drop_constraint('planets_terrain_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_terrain_key', ['terrain'])
        batch_op.create_unique_constraint('planets_climate_key', ['climate'])

    # ### end Alembic commands ###
